# https://circleci.com/docs/2.1/language-javascript/
version: 2.1
commands:
  extract-changelog-version:
    steps:
      - run:
          name: extract changelog version
          working_directory: ~/log
          command: |
            VERSION=$(head -n1 CHANGELOG.md | grep -o '\([0-9]\+\.\)\{2\}[0-9]\+')
            echo "export VERSION=${VERSION}" >> $BASH_ENV
            echo "export CHANGELOG_VERSION=${VERSION}" >> $BASH_ENV
            echo "changelog version: ${VERSION}"

  extract-package-json-version:
    steps:
      - run:
          name: extract package.json version
          working_directory: ~/log
          command: |
            PACKAGE_JSON_VERSION=$(node -e "console.info(require('./package').version)")
            echo "export PACKAGE_JSON_VERSION=${PACKAGE_JSON_VERSION}" >> $BASH_ENV
            echo "package.json version: ${PACKAGE_JSON_VERSION}"

  extract-published-version:
    steps:
      - run:
          name: extract latest published version
          working_directory: ~/log
          command: |
            LIVE_VERSION=$(npm show @haensl/log version || true)
            [ -z "${LIVE_VERSION}" ] && LIVE_VERSION='0.0.0'
            echo "export LIVE_VERSION=${LIVE_VERSION}" >> ${BASH_ENV}
            echo "latest published version: ${LIVE_VERSION}"

  extract-versions:
    steps:
      - extract-changelog-version
      - extract-package-json-version
      - extract-published-version

  init:
    steps:
      - run:
          name: update npm
          command: sudo npm install -g npm@latest

  prepare-repo:
    steps:
      - checkout
      - restore_cache:
          keys:
            - log-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: log-dependencies-{{ checksum "package-lock.json" }}
      - extract-versions

workflows:
  default:
    when: always
    jobs:
      - lint
      - test
      - ensure-versioned-correctly
      - bundle
      - publish:
          requires:
            - ensure-versioned-correctly
            - bundle
          filters:
            branches:
              only: master
      - publish-github-release:
          requires:
            - publish

jobs:
  lint:
    docker:
      - image: cimg/node:lts
    working_directory: ~/log
    steps:
      - init
      - prepare-repo
      - run:
          name: create test-results-folder
          command: mkdir -p test-results/eslint
      - run:
          name: lint
          command: npm run lint:junit
      - store_test_results:
          path: test-results

  test:
    docker:
      - image: cimg/node:lts
    working_directory: ~/log
    steps:
      - init
      - prepare-repo
      - run:
          name: unit tests
          command: npm run test:junit
      - store_test_results:
          path: test-results

  ensure-versioned-correctly:
    docker:
      - image: cimg/node:lts
    working_directory: ~/log
    steps:
      - init
      - prepare-repo
      - extract-versions
      - run:
          name: changelog matches package.json
          command: |
            test ${PACKAGE_JSON_VERSION} = ${CHANGELOG_VERSION}
      - run:
          name: package.json greater than live
          command: |
            node \<<VERSION_CHECK
            const pkgVersion = require('./package').version
              .split('.')
              .map((i) => parseInt(i, 10));
            const liveVersion = process.env.LIVE_VERSION
              .split('.')
              .map((i) => parseInt(i, 10));
            const isGreater = pkgVersion.reduce((isGreater, part, i) => {
              return isGreater || (part > liveVersion[i]);
            }, false);
            if (!isGreater) {
              process.exit(1);
            }
            VERSION_CHECK

  bundle:
    docker:
      - image: cimg/node:lts
    working_directory: ~/log
    steps:
      - init
      - checkout
      - run:
          name: bundle
          command: npm pack
      - persist_to_workspace:
          root: ./
          paths:
            - haensl-log-*.tgz

  publish:
    docker:
      - image: cimg/node:lts
    working_directory: ~/log
    steps:
      - init
      - prepare-repo
      - run:
          name: setup npm registry token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: publish node module
          command: npm publish --access public

  publish-github-release:
    docker:
      - image: cibuilds/github
    working_directory: ~/log
    steps:
      - checkout
      - extract-changelog-version
      - attach_workspace:
          at: ~/log
      - run:
          name: publish github release
          working_directory: ~/log
          command: |
            CHANGES=$(awk "/## ${VERSION}/,/^$/" CHANGELOG.md)
            echo "Publishing release v${VERSION} to Github.\nChanges:"
            echo $CHANGES
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete -n "v${VERSION}" -b "${CHANGES}" "v${VERSION}" ./haensl-log-${VERSION}.tgz
